### ISSUE TITLE
Permissions as an array of abilities  doesn't work properly 

### ISSUE THREAD

**Issue by ionutvladu** [victorybiz/vue-simple-acl#12]
There is a bug in VueSimpleAcl.ts at line 137 
https://github.com/victorybiz/vue-simple-acl/blob/a566763274f40dccac89f8832db092bb188e1239/src/VueSimpleAcl.ts#L137

The if condition is not good
```
callbackResponse =  evaluateAbilityCallback(callback, ability.abilities, ability.args);
        if (validCount) {
          validCount++;
        }
```

the fix is 

```  
       callbackResponse =  evaluateAbilityCallback(callback, ability.abilities, ability.args);
        if (callbackResponse ) {
          validCount++;
        }
```

**Comment by victorybiz** [comment]
Thank you @ionutvladu , issue fixed in [v2.0.2](https://github.com/victorybiz/vue-simple-acl/releases/tag/v2.0.2)
