### ISSUE TITLE
ReferenceError: Vue is not defined

### ISSUE THREAD

**Issue by paramov** [victorybiz/vue-simple-acl#7]
Can you help me?

**Comment by IssamJow** [comment]
I have the same Problem, did you figure it out?

**Comment by victorybiz** [comment]
@IssamJow 
I haven't  had time to look into this, please use this to solve this issue for now:
```js
import { createAcl, defineAclRules } from 'vue-simple-acl/src';
```

**Comment by oliverkan** [comment]
@victorybiz is there any solution to this problem? I tried to import your plugin into Vue3 (version 3.2.37) but `import { createAcl, defineAclRules } from 'vue-simple-acl/src';` solution didn't work. Can you help us to fix this problem please? This a nice library and it would be nice to keep it updated.
